title: Jon Stevens # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey there! I'm a C#/C++ developer who loves making multiplayer games!
  <br><br>
  My greatest achievement so far is building the core architecture for Kerbal Space Program 2 to support a robust simulation and long-term feature goals like multiplayer.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github:
  is_project_page: false
